### ISSUE TITLE
Scribus frame render not updating with specified gabc

### ISSUE THREAD

**Issue by nighthawkuofl** [gregorio-project/gregorio#1531] opened 2021-02-26 06:01 UTC
When rendering a gregorio render frame in Scribus, the scribus_file-score.gabc does not update to use the text indicated in the source code. Instead, that .gabc file is used for all frames unless and until deleted, which allows for proper rendering on the next occurrence. If it makes any difference, I am using Windows 10.

**Comment by rpspringuel** [comment] 2021-02-26 16:43
Possible duplicate of #1523 (which is already fixed).

**Comment by nighthawkuofl** [comment] 2021-02-26 21:42
Making the changes specified there worked. Thanks for referencing me. I obviously didn't sift enough through Google.

**Closed** 2021-02-26 22:38 UTC
