### ISSUE TITLE
Move font glyphs to UCS Private Use Area

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#239] opened 2015-04-08 12:21 UTC
See earlier part of the discussion in #232.

**Comment by henryso** [comment] 2015-04-08 12:25
According to [Wikipedia](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Private_use), there are 137468 private use code points at U+E000 to U+F8FF, U+F0000 to U+FFFFD, and U+100000 to U+10FFFD.  How many glyphs do we currently use?

**Comment by henryso** [comment] 2015-04-08 12:33
If that's not enough, I *think* it's possible to reduce the number of code points needed by using multiple characters to select a glyph (similar to how ligatures like `ffi` work in Unicode fonts).

**Comment by eroux** [comment] 2015-04-08 12:37
The number of glyph is not really the most important, it's ridiculously low: 3137. The problem is how they are organized. Currently (look at lines 343 for `squarize.py` or in `gregoriotex-write.c`), the glyph is assigned to:

 * with ambitus (x) = ambitus between the xth note and the x+1th note
 * 512*shape + 256*liquescence + 25 * ambitus(3) + 5* ambitus(2) + ambitus(1)
 * or if it has only two notes: 512*shape + 64*liquescence + ambitus(1)

so it's a convention that allows gregoriotex to know the glyph number quite easily. The problem is that it takes quite some room, so currently the gregorio glyphs are between code points `u+00A2` (162) and `u+6FC3`, which is much bigger than the number of glyphs, but allows an easy computation. This makes 28611 code points used by Gregorio. Well, it largely fits into PUA-A, so let's do that!

**Comment by eroux** [comment] 2015-04-08 12:40
A question that needs a quick answer is: do we do that for 3.0.0? This would seem wise to be, but we need to make sure that scores computes with 3.0.0-rc1 will be recomputed.

**Comment by henryso** [comment] 2015-04-08 13:24
For me, it depends on the potential to break things that are working (other than the font issues from last time).  It doesn't sound like that's too much of a problem, and if that's the case, then I'm fine with 3.0.0.

**Comment by eroux** [comment] 2015-04-08 13:29
Well it might not be a problem from the user point of view... The only possible problems users might encounter are with other special characters in Unicode that are interpreted by other softwares (like small spaces, etc.). There might be Gregorio glyphs on these... And it would allow to finish things clean and be future-proof... cleaning things is in the air these days, I think it would be a good opportunity.

**Comment by rpspringuel** [comment] 2015-04-08 18:44
I don't think there's a need to worry about code point conflicts in the private use areas. Our fonts don't get used much (if at all) outside of typesetting a score and other fonts are unlikely to appear inside of a score (at least within the notes).

**Comment by henryso** [comment] 2015-04-08 18:57
So the verdict is ... do it in 3.0.0?

**Comment by eroux** [comment] 2015-04-08 19:20
The main advantage of PAU is precisely the lack of code point conflicts, which may appear in the current state. Well, if a vote seems relevant to you, I vote for 3.0.0.

**Closed** 2015-04-09 13:32 UTC
