### ISSUE TITLE
custos placed improperly with multiple voices

### ISSUE THREAD

**Issue by asbloomf** [gregorio-project/gregorio#1069] opened 2016-04-11 16:52 UTC
The custos is placed according to the first note in brackets instead of the unbracketed one.

For examle, the following puts the custos at the g instead of the c.

`\gabcsnippet{Et(ez) quid({gr}c)}`

[example.zip](https://github.com/gregorio-project/gregorio/files/213448/example.zip)

**Comment by eroux** [comment] 2016-04-17 09:35
Looking at gregorio code, the glyphs between `{}` are meant to be placed after the normal ones in the gabc, for instance `quid(c{gr})`. Maybe just documenting this would also solve #1070.

**Comment by henryso** [comment] 2016-05-28 01:44
Are we agreed that documentation is the way to fix #1069 and #1070?

**Comment by rpspringuel** [comment] 2016-05-28 02:42
If it's not too difficult, raising a warning about the unsupported notation would be in order, but otherwise I agree that simply documenting the fact that bracketed notes are expected to come second is sufficient.

**Comment by henryso** [comment] 2016-05-28 02:54
There's no way to tell the difference between placing it after the note before it and placing it before the note after it.

**Comment by rpspringuel** [comment] 2016-05-28 02:59
But if `\gabcsnippet{Et(ez) quid({gr}c)}` and `\gabcsnippet{Et(ez) quid(c{gr})}` produce different results, doesn't that imply that gregorio knows the difference between them?

Or is the problem that `\gabcsnippet{Et(ez) quid({gr}c)}` and `\gabcsnippet{Et(ez) quid(gr{c})}` are indistiguishable?

**Comment by henryso** [comment] 2016-05-28 03:03
The problem is that if you have something like `(a{b}c)` and you *mean* `(ab{c})`, there's no way to tell the difference.

**Comment by rpspringuel** [comment] 2016-05-28 13:40
Uhg.  I would call `(a{b}c)` a serious syntax error, but if the lexer can't distinguish it from `(ab{c})` then I guess we can't tell the user that anywhere but the documentation.

Is there no way to programmatically say if braced notes are used then the closing brace *must* come directly before the closing parentheses?

**Comment by henryso** [comment] 2016-05-28 14:16
If I had all the rules of correct usage of this thing, then maybe I could answer that, but I don't know what they are.

**Comment by henryso** [comment] 2016-05-28 14:58
After playing with this for a bit, I think @eroux's statement is wrong.  I don't think putting the braces after the note produces the correct result.

If I understand the feature (and I can't say I do, completely), this hacky feature allows you to typeset some sequence of gabc on top of some other sequence of gabc.  The open brace inserts `\hbox to 0 pt{`, and the close brace inserts `\hss}\GreNoBreak\relax`.  This tells me that the braces need to come *before* the notes that should be overlaid.

For #1069 (this issue), either we state that the custos will be placed according to the first note in the brackets and be done with it, or we modify it so that the custos algorithm ignores the bracketed notes.  This is a relatively complex fix, since we will need to make the bracket handling into something more complex than a texverb.

For #1070, either we state that the longer sequence should be the unbracketed one or we create some macro or something that allows TeX to choose between the maximum sizes of both glyphs (I admit I have no idea how to do this in TeX).

I think one should be fixed by documentation and the other by code so that the user can control which sequence implies the custos.  Any thoughts?  Any ideas how to code #1070 so we can choose a path forward?

**Comment by rpspringuel** [comment] 2016-05-29 19:10
My thoughts:

We need some mechanism for distinguishing the primary voice from the secondary.  My inclination is to say that the bracketed notes in the gabc are the secondary.

Given that, then the custos should follow the primary voice only.  I think that if we required the bracketed notes to come second, then the existing custos determining algorithms would work just fine, making this largely a documentation change (though perhaps a syntax error if the correct order of bracketed and non-bracketed notes is not observed would be in order).

To get the spacing right, I would define a `\GreSecondaryVoice` macro which puts the bracketed notes into their own box, and then does some magic with the widths of it and the box containing the primary voice.  What sort of magic is needed here depends largely on how we want this to function.  I have some ideas here, but need some time to flesh them out so that I can post them coherently.

**Comment by henryso** [comment] 2016-05-29 20:37
Besides working out how `\GreSecondaryVoice` would work (from a technical standpoint), we need to decide or clarify the following:

- Should the secondary voice come first (which is backward compatible) or second?
- Should the secondary voice be at the element (= non-breakable neume group) level or at the syllable level.  I don't know which of these is the backward compatible option.
- Should we allow more than one secondary voice?  I don't see why not.

**Comment by rpspringuel** [comment] 2016-05-30 00:29
> Should the secondary voice come first (which is backward compatible) or second?

While I'm all for backward compatibility, it strikes me as more logical that the secondary voice should come second.

> Should the secondary voice be at the element (= non-breakable neume group) level or at the syllable level. I don't know which of these is the backward compatible option.

I'm inclined to follow the nabc model here and make it be at the element level.  This would allow for finer synchronization between the notes in the two voices.  This might also indicate what our implementation path should be, as we could probably borrow from the nabc code.

> Should we allow more than one secondary voice? I don't see why not.

Again, I would be inclined to follow the nabc model here and make that a future feature.  It's going to be hard enough to get one secondary voice implemented.  Implementing an arbitrary number would be even harder.

**Comment by rpspringuel** [comment] 2016-05-30 01:50
Having looked at the nabc mechanism, I'm less convinced that borrowing from it is feasible.  The nabc mechanism is to piggy-back on the above line text and basically amounts to "print this glyph now but pretend it doesn't take up any space".  Since this the printing is happening above the staff and the nabc glyphs are generally small, this doesn't present any major spacing problems, where as the neumes which go into a secondary voice are expected to be in the staff with the primary voice and may very well be longer than the primary.

**Comment by eroux** [comment] 2016-05-30 04:58
I also agree that the secondary voice should come second, but from a technical point of view, this is really the most difficult solution, so I'm not really sure what's best... This feature is not used a lot, maybe it's not worth the burden? I'd also be enclined to consider them at element level and to allow multiple secondary voices, but only if it's not too complex... (I think allowing multiple ones should be straightforward though, it should even work with the current code)

**Comment by henryso** [comment] 2016-05-30 12:23
I'm not sure how feasible this is in TeX, but I see it as something like:

```
\GreElementVoices{
  \GreElementVoice{%
    ... glyphs ...
  }%
  \GreElementVoice{%
    ... second voice glyphs ...
  }%
}%
```

Each `\GreElementVoice` would measure and build a box that overlays the "voice".

`\GreElementVoices` first executes its `#1` to build the box of overlaid voices, then emits the box and sets the width to the maximum of measured widths.

That said, if this feature is really not well used, then maybe we should just leave it as the hack it is, warts and all, and just document how to use it, noting its quirks.  Maybe we should ask the list to see if anyone uses this?

**Comment by eroux** [comment] 2016-05-30 17:09
Your algorithm is what should actually be done for nabc (I think), but I'm not sure it's very easy to implement (I'm not sure it's hard neither). For this feature, I think asking the list is indeed a good idea

**Comment by henryso** [comment] 2016-07-04 17:35
Closing as wontfix, in deference to documentation in gregorio-project/gregorio-project.github.io#41.

**Closed by henryso** 2016-07-04 17:35 UTC
Labels: bug, wontfix
