### ISSUE TITLE
Bad spacing on scores without words

### ISSUE THREAD

**Issue by benyanke** [gregorio-project/gregorio#1226] opened 2016-09-14 02:23 UTC
In this office hymn score, the spacing of the first note collides with the clef on the first line. I have also noticed this behavior in the past as well, requiring a lot of manual space additions.

```
(f3) (h) (h) (i) (j) (i) (i) (h) (g_) (,) 
(i) (g) (h) (f) (e) (h) (h) (h.;) 
(h) (h) (i) (j) (i) (i) (h) (g_) (,) 
(i) (g) (h) (f) (e) (h) (f) (f.) (::) 
A(fgf)men.(ef..) (::) 
```

![image](https://cloud.githubusercontent.com/assets/4274911/18497943/2cf2bdfa-79f8-11e6-8238-30ec11671a9e.png)

**Comment by henryso** [comment] 2016-09-28 00:44
Please provide the (portion of the ) `.tex` file you use to generate that output.

**Comment by henryso** [comment] 2016-10-01 12:12
@benyanke I cannot reproduce this problem with the latest Gregorio.  Please provide the TeX file used to generate the attached output.  Which version of Gregorio are you using?

**Comment by henryso** [comment] 2016-11-08 00:36
@benyanke Can you provide files that have this problem?  If not, I will close this as not reproducible.

**Comment by henryso** [comment] 2016-12-18 03:05
Closing as not reproducible.

**Closed by henryso** 2016-12-18 03:05 UTC
Labels: not reproducible

**Comment by benyanke** [comment] 2016-12-18 03:55
Sorry, I somehow missed this earlier. In any case, here's the tex (I believe). I'm running it here: `http://dev.illuminarepublications.com/gregorio/
`
[gregorio5856081c8d4487.44729005.pdf](https://github.com/gregorio-project/gregorio/files/659230/gregorio5856081c8d4487.44729005.pdf)

[gregorio5856081c8d4487.44729005.tex.txt](https://github.com/gregorio-project/gregorio/files/659231/gregorio5856081c8d4487.44729005.tex.txt)

[score.gabc.txt](https://github.com/gregorio-project/gregorio/files/659232/score.gabc.txt)

**Comment by henryso** [comment] 2016-12-18 06:24
This doesn't happen with the current version of the gregorio.  You'll have to take it up with the folks at Illuminaire to upgrade or run it locally yourself.

**Comment by benyanke** [comment] 2016-12-18 20:51
I've passed it along. Thanks!
