### ISSUE TITLE
name of the executable for TeXLive

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1292] opened 2017-02-03 13:53 UTC
Following a private discussion, it seems we have to provide an executable named `gregorio` for TeXLive (no version number appended). I see two ways to do that:

- first is to alter the build process and have a texlive option to build a binary without the file version appended (and also modify the .tex files accordingly)
- the other is to just always remove the version number and have a check on `gregorio --version` before the first score compilation

What do you think?

**Comment by rpspringuel** [comment] 2017-02-03 15:34
> first is to alter the build process and have a texlive option to build a binary without the file version appended (and also modify the .tex files accordingly)

Looking back at 5c364568, I think there are just three files that would need to be altered on this route: `src/Makefile.am` (to create a build target for the TeXLive release), `doc/Makefile.am` (to allow TeXLive developers to build the docs), and `gregoriotex.lua` (to get the package looking for the right executable).  I don't think the other files which were modified in that commit are needed by the TeXLive people (`macosx/douninstall.sh` and `windows/gregorio.iss` are for creating our installers and `contrib/gregorio-scribus.lua` doesn't end up in TeXLive.  However, I don't know how difficult it would be to get `make` to alter `gregoriotex.lua` as part of a texlive build target, so I'll defer to others on the actual feasibility here.

> the other is to just always remove the version number and have a check on gregorio --version before the first score compilation

I had written code to do that check before we decided to append the version number to the executable name, so it's certainly possible.  The bigger issue with this route is what to do if the version number doesn't match.  When this happens, it's most likely due to the individual having two versions of gregorio installed, the one in TeXLive and one which they have installed manually.  Should our code account for this and look for multiple versions of the executable and check each of them, and if one of them works use it?  If so, there's a complication in the fact that on unix-like systems and Windows the commands for finding executables are different (`which -a` vs. `where /f`).  We thus would have to detect which OS we're running under some how and my preliminary searching tells me lua doesn't have an easy way to do this (though there are several work arounds proposed in various places).

**Comment by henryso** [comment] 2017-02-03 16:05
Having no version number for the non-TeX-Live version will cause problems because of the PATH-variable-related stuff that we ran into last year.  Since TeX Live requires no version number, then the TeX Live release will have no version number and all installer releases will have a version number.

I suggest keeping a TeX-Live-specific branch in the ctan branch with version numbers stripped as our burden and have TeX-Live-specific source-only releases from that branch.  So, let's say we release 5.0.0 for TeX Live, we would actually make two separate releases, 5.0.0 and 5.0.0-texlive.  The 5.0.0-texlive release would be source-only.  In the mid-year, we might release 5.0.1 and 5.1.0 in the usual way (with installers), and then release 5.2.0 and 5.2.0-texlive when the next TeX Live comes around.

Our code should simply ignore the TeX Live version, other than looking for the version-less executable for reporting from the system-setup.command stuff.

What do you think?

**Comment by rpspringuel** [comment] 2017-02-03 16:52
My concern with that strategy is the ability to merge changes in and out of the ctan branch.

For instance, assume 5.0.0 is in TeXLive.  We then get a bug report which can be traced back to just the TeX code and we decide to release 5.0.1 and push it to CTAN.  If we make the changes on the ctan branch and then merge them into develop, will this bring in the changes which stripped off the version number?  What about when it comes time for the next TeXLive release?  Do we have to manually strip off the version number to create a new ctan branch for that?  

If you recall we had some issues in gregorio-test where some defective tests kept getting merged back into the repository.  I don't want to set ourselves up for that sort of merge issue to be an annual event.  Whether we prevent the problem by doing something different or by implementing some procedural standards doesn't really matter to me, just so long as we do something.

Oh, and it should be noted that `system-setup.command/bat' already looks for both versioned and unversioned executable names.

**Comment by henryso** [comment] 2017-02-03 17:44
Unfortunately, with this requirement, we just have to deal with the burden of fixing up the version numbers when ctan is merged into develop (or whatever) and vice versa.  I don't see a way around this, which is one of the reasons we decided to put the number in at all times (which now we can't do).

**Comment by henryso** [comment] 2017-02-03 17:45
That said, if you have an idea that will work, I'm open to it.

**Comment by eroux** [comment] 2017-02-03 17:50
I agree with @henryso 's proposal here, although I admit it's an additional burden

**Comment by rpspringuel** [comment] 2017-02-04 15:02
Here's a code snippet that uses lua to identify the full path to an executable with the appropriate version number:

```
local internalversion = "3.2.57"
local executable = nil

test = io.popen("which -a bash")
while true do
    local line = test:read()
    if line == nil then break end
    second = io.popen(line.." --version")
    second = string.match(second:read("*line"),"%d+%.%d+%.%d+[-a-z0-9]*")
    if second == internalversion then
        executable = line
        break
    end
end
print(executable)
```

I've used `bash` for this test case because I know I have two versions of it on my system and thus it forms an ideal test (I don't currently have two versions of `gregorio`).  This works fine on Mac, and I think it should work on Linux (no time to test right now), but won't work on Windows (`which` doesn't exist there).  I've got a funeral to go to right now (one of my confreres died last week), but when I get back I'll see about expanding it to work on Windows too.

**Comment by henryso** [comment] 2017-02-04 15:42
Is which on shell_escape_commands?

**Comment by eroux** [comment] 2017-02-04 15:52
no, so this is not a possible solution

**Comment by henryso** [comment] 2017-02-04 15:54
@rpspringuel I think you may be on to something here, though...

1. Lua can simply look for (or outright try calling) gregorio-{version} and then gregorio.
2. The executable could emit something like `\GreRequires({version})` that would raise an error if the version mismatches

**Comment by rpspringuel** [comment] 2017-02-04 20:00
> The executable could emit something like \GreRequires({version}) that would raise an error if the version mismatches

This check would actually be better done as part of package loading, since it'll be the same for all scores in a document.  I've written that check before and it looks something like this:
```
local exe_version = io.popen(gregorio_exe--" --version")
exe_version = string.match(exe_version:read("*line"),,"%d+%.%d+%.%d+[-a-z0-9]*")
if exe_version != internalversion then
    err("Version mismatch!\n".."Executable and GregorioTeX are not compatible")
end
```

> Lua can simply look for (or outright try calling) gregorio-{version} and then gregorio

The problem is that `gregorio` might exist in two locations.  For instance, on a Mac there would be one in `/Library/TeX/texbin/gregorio` (the binary packaged in TeXLive) and `/usr/local/bin/gregorio` (the user installed version).  A blind call would just get us the first in `$PATH`.  If the right one happens to be second, we have to use something like `which -a` to find it.

Hmm...  Lua does have `io.getenv`.  I might be able to use that to basically rewrite the functionality of `which` completely in Lua.  Let me play with that idea for a bit.

**Comment by henryso** [comment] 2017-02-04 20:15
If the user-installed gregorio always has the version number, then gregorio will only exist in the TeX Live installation.

**Comment by rpspringuel** [comment] 2017-02-04 20:34
Right, I'm thinking of a situation where both are named `gregorio` to try and avoid the extra maintenance that having separate names would involve.

Here's another code snippet which avoids reliance on `which`.  As a bonus, this should also work on Windows because the variable we're accessing (`PATH`) has the same name.  I haven't tested that though:

```
local internalversion = "3.2.57"
local executable = nil

first = os.getenv("PATH")
for i in string.gmatch(first,"[^:]*") do
    if i ~= "" then
        temp = i.."/bash"
        second = io.popen(temp.." --version 2>/dev/null")
        second = second:read("*line")
        if second then
            second = string.match(second,"%d+%.%d+%.%d+[-a-z0-9]*")
            if second == internalversion then
                executable = temp
                break
            end
        end
    end
end
print(executable)
```

The question here is whether the invocation by full path will work given that `gregorio` is in the shell_escape_commands without any path attached.

**Comment by henryso** [comment] 2017-02-04 21:03
Invocation with full path will fail on shell_escape_commands.  I tested that before when we were messing with the PATH stuff considering this problem last year.

We can consider a way to choose whether gregorio has the version number appended in the Makefile.  If we can figure that out and gregoriotex.lua can run the executable with the version number or not, then there should be less of an issue, no?

Additionally, the above code will not work under Windows, which uses the semicolon as path separator.

**Comment by rpspringuel** [comment] 2017-02-04 22:25
> Invocation with full path will fail on shell_escape_commands. I tested that before when we were messing with the PATH stuff considering this problem last year.

Well, nuts.  That kind of closes off my idea completely.

> We can consider a way to choose whether gregorio has the version number appended in the Makefile. If we can figure that out and gregoriotex.lua can run the executable with the version number or not, then there should be less of an issue, no?

That should work.  See rpspringuel/gregorio@4fb376c0 for untested lua code which should enable that portion of the fix.

**Comment by a-kakuto** [comment] 2017-02-05 10:22
Please don't bother to make a TeX-Live-specific version
without the version number in the executable.
Sorry for my inappropriate statement in a previous mail to you.
We can use the executable name with the version number
also in TeX Live, if you think that gregorio-$FILENAME_VERSION is
convenient. We will update gregorio-$FILENAME_VERSION and
shell_escape_commands once a year. It is not a big deal.

Best, Akira Kakuto

**Comment by henryso** [comment] 2017-04-14 23:29
Based on an email from Karl Berry, I think we need to reopen this.

**Comment by henryso** [comment] 2017-04-14 23:39
I'll take this on based on rpspringuel/gregorio@4fb376c, with the idea of having a configure flag for texlive, but it'll probably take me a few days, so I don't think it will make 5.0.

**Comment by eroux** [comment] 2017-04-15 06:53
I won't be here today, but here are a few remarks:

- I'm not sure `enable-texlive` is the best choice for the config option, maybe `disable-version-in-exe`? but it doesn't matter much
- if the things you're not sure about are in the Lua code, it's certainly worth releasing a 5.0.0 today and fixing the bugs that may appear in the lua code in a 5.0.1 in a few days, changing only the Lua code...

So my opinion would be to merge #1350 and make a release today (with or without the change of config option)... Thank you!

**Comment by a-kakuto** [comment] 2017-04-15 07:05
Hi,

I think that Karl will admit FILENAME_VERSION
if it is convenient for you.

Thanks,
Akira

**Comment by a-kakuto** [comment] 2017-04-15 07:35
If you use FILENAME_VERSION in non-TeX Live case,
use it also in TeX Live.  I think that it is better
not to distinguish TeX Live.

Best,
Akira

**Comment by a-kakuto** [comment] 2017-04-15 07:50
Sorry that my opinion has changed from the beginning,
that may be a reason of this issue:
"name of the executable for 'TeXLive'".

If you don't use FILENAME_VERSION anywhere, I think
it is the best. However if you use it, please don't bother
to make TeXLive-specific version.

Thanks,
Akira

**Comment by henryso** [comment] 2017-04-15 12:28
`FILENAME_VERSION` is used elsewhere.  The proposed change for this issue will include a new Makefile variable, `GREGORIO_EXE_SUFFIX`, which can be set to "blank" by running `configure` with `--disable-version-in-exe`

**Closed** 2017-04-15 13:26 UTC
Labels: build/install
