### ISSUE TITLE
Clef shows up at the end of a line if an alteration immediately follows it on the next line

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1477] opened 2019-10-31 01:12 UTC
I'm not 100% sure the cause is the alteration, but it appears to be the cause.  The workaround, of course, is to put an `nlba` somewhere so the alteration moves from that position.

![image](https://user-images.githubusercontent.com/421318/67910584-afb44980-fb59-11e9-86fe-7845e1bf250c.png)

MWE here: [mwe.zip](https://github.com/gregorio-project/gregorio/files/3791686/mwe.zip)

**Comment by cantatedomino** [comment] 2019-12-18 17:03
I'm glad I checked the open issues -- I ran into the same issue with Urbs fortitudinis recently, and didn't notice it until the choir sang it ...
<img width="859" alt="Screen Shot 2019-12-18 at 09 02 46" src="https://user-images.githubusercontent.com/59026582/71107019-2f7f8d00-2175-11ea-8a8d-ebfe54e00fee.png">

**Comment by olivierberten** [comment] 2021-08-16 06:49
Duplicate of #1477

**Closed by olivierberten** 2021-08-16 06:49 UTC
Labels: bug, TeX

**Comment by olivierberten** [comment] 2021-08-16 06:50
Duplicate of #1373

**Comment by JacquesPerriere** [comment] 2024-01-23 23:23
On GregoBase [score 1206](https://gregobase.selapa.net/chant.php?id=1206) the bug 1373 at the end of line 1 disappeared after adding this little TeX command:
`\gresetcustosalteration{invisible}`
