### ISSUE TITLE
fifge is apparently not rendering correctly

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#155] opened 2015-03-25 22:42 UTC
In `completetest.gabc`, noticed that the (`fifge`) figures are apparently not rendering correctly unless this is a figure I am unfamiliar with.  There is no line between the `f` and the `i`.

**Comment by eroux** [comment] 2015-03-27 08:13
It's not currently possible to draw complete neumes of five notes, as this would make `5^4=625` glyphs per liquescence type... I don't really know how to deal with this yet, maybe it could be done on the TeX side, but I'm affraid this will be less precise (though these glyphs are really not common)...

Anyway, this is a duplicate of #18

**Closed** 2015-03-27 08:13 UTC
Labels: duplicate, fonts
