### ISSUE TITLE
TeX Live 2016 test breaks

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#1199] opened 2016-08-06 18:43 UTC
Under TeX Live 2016 (but not TeX Live 2015), the `plain-tex/PopulusSion/PopulusSion.tex`, `plain-tex/braces/over_braces.tex`, and `plain-tex/text-styles/text-styles.tex` tests fail with:
```
infwarerr: The package is already loaded, stopped
) (/usr/local/texlive/2016/texmf-dist/tex/generic/oberdiek/ltxcmds.sty
ltxcmds: The package is already loaded, stopped
)
! Undefined control sequence.
<argument> ...degraphics \@undefined \else \@ifpackageloaded 
                                                  {pst-pdf}{}{\@ifpackageloa...
\AtBeginDocument #1->#1
                       
l.1271   }
        
? 
! Emergency stop.
<argument> ...degraphics \@undefined \else \@ifpackageloaded 
                                                  {pst-pdf}{}{\@ifpackageloa...
\AtBeginDocument #1->#1
                       
l.1271   }
        
End of file on the terminal!

!  ==> Fatal error occurred, no output PDF file produced!
```

The custom spaces also appear to be broken under TeX Live 2016.  See the `gabc-output/glyphs/spaces.gabc` test:

![image](https://cloud.githubusercontent.com/assets/421318/17458604/15965d2e-5be4-11e6-92b9-46a0e712a51d.png)

**Comment by rpspringuel** [comment] 2016-08-14 00:20
The `plain-tex` tests are failing due to some sort of package loading error with graphicx and xcolor.  I can reproduce them with the following simple document:

```
%%%%%%%%%%%%%%%%%%
%% TeXLive 2016 compatibility
\ifdefined\pagewidth                   \let\pdfpagewidth       \pagewidth                  \fi
\ifdefined\pageheight                  \let\pdfpageheight      \pageheight                 \fi
%%%%%%%%%%%%%%%%%%

\pdfpagewidth210mm
\pdfpageheight297mm

\edef\greoldcatcode{\the\catcode`@}
\catcode`\@=11

\input graphicx.tex % for \resizebox
\input color.sty%

\catcode`\@=\greoldcatcode

\color{red}
Hello!
\bye
```

This only occurs under LuaTeX.  pdfTeX handles the above document fine.  We're thus probably looking at a LuaTeX bug.  @eroux, where was it that we were supposed to report such bugs again?

**Comment by eroux** [comment] 2016-08-15 07:57
Do you have an up to date TeXLive 2016? A similar problem was reported [here](http://tug.org/pipermail/tex-live/2016-June/038830.html) but it seems to have been fixed... if it's not, I think the mailing list of the thread is the correct one...

**Comment by rpspringuel** [comment] 2016-08-15 13:56
I'm fully up to date (just checked).

After some more experimenting I've discovered that I can work around the issue as follows:

```
%%%%%%%%%%%%%%%%%%
%% TeXLive 2016 compatibility
\ifdefined\pagewidth                   \let\pdfpagewidth       \pagewidth                  \fi
\ifdefined\pageheight                  \let\pdfpageheight      \pageheight                 \fi
%%%%%%%%%%%%%%%%%%

\pdfpagewidth210mm
\pdfpageheight297mm

\edef\greoldcatcode{\the\catcode`@}
\catcode`\@=11

\input miniltx.tex
\input color.sty%
\input graphicx.tex %

\catcode`\@=\greoldcatcode

\color{red}
Hello!
\bye
```

**Comment by eroux** [comment] 2016-08-15 14:01
Well, this still looks like a bug, so I think it would be best to report it to tex-live mailing-list

**Comment by rpspringuel** [comment] 2016-08-15 14:25
Well, it doesn't appear to me to be a TeXLive packaging problem, so I'm not sure that's the right place.  Since the problem appears related to graphicx and color, I just reported it to the LaTeX project using their bug reporting form (as they are the maintainers of those packages).

**Comment by eroux** [comment] 2016-08-15 14:29
Ok thanks

**Comment by rpspringuel** [comment] 2016-08-16 20:32
For future reference, bug reports on the PlainTeX interface of color and graphicx should go to one of the following places:

https://github.com/davidcarlisle/dpctex/tree/master/plain-graphics

or

https://github.com/latex3/graphics-def

**Comment by rpspringuel** [comment] 2016-08-17 00:58
The PlainTeX problems are addressed in #1207.  Even without those changes, however, they should be solved when the fix (which has already been pushed to CTAN) makes it to the download mirrors in 24 hours or so.

The problem with the custom spacings remains.

**Comment by rpspringuel** [comment] 2016-08-18 14:37
I just did some experimenting and it seems that adding a `tex.setskip` command into `gregoriotex.lua` in the appropriate place fixes the issue with the custom spacings.  My guess is that the scaling in Lua is no longer being communicated implicitly back to TeX, so we have to do it explicitly ourselves.

I've made the fix locally, I'm just debating which release to push it to.

**Comment by henryso** [comment] 2016-08-18 15:32
Is setting tex.setskip backward compatible to at least TeX Live 2015?  It seems like that should go into 4.1.x, along with @anthonyfok's change, if that can be vetted.

**Comment by rpspringuel** [comment] 2016-08-18 17:24
I'm in the process of checking backwards compatibility.  I'll let you know the results when I have them.

**Comment by rpspringuel** [comment] 2016-08-19 01:49
The change is backwards compatible with TL2015.

**Comment by henryso** [comment] 2016-08-21 12:52
Any clues to the cause of the custom spacing issue?

**Comment by rpspringuel** [comment] 2016-08-21 18:13
I have my suspicion (given above), but nothing more at the moment.  I just sent an email to the LuaTeX list asking about the change to see if my suspicions are correct.

**Comment by rpspringuel** [comment] 2016-08-22 15:37
The reply I got from the LuaTeX list:

> skips (glue) is kind of special in the sense that it's something indirect (glue specs)

> in the current luatex the glue nodes no longer use these specs (so no indirectness) but the registers are still 'specs' so, what you get with
tex.getskip is a gluespec (node) that you can then mess with (independently) and you set a skip by passing a gluespec node

> (the old model also shared specs with ref counts and such which could be quite tricky and have side effects when messing with these specs)

> you can use tex.setglue to set the width (or more values) 

If I understand the jargon correctly, then my suspicion is correct and the fix I applied is the appropriate one.

**Closed by rpspringuel** 2016-08-22 15:37 UTC
Labels: bug, TeX

**Comment by henryso** [comment] 2016-08-22 15:39
... and since you confirmed earlier that this is backwards-compatible, it's all good.  Thanks for following up.
