### ISSUE TITLE
Flats valid for a whole line <> reflow

### ISSUE THREAD

**Issue by olivierberten** [gregorio-project/gregorio#1398] opened 2018-01-03 09:48 UTC
No idea whether it's possible for gregorio to deal with this but I still wanted to document that case:

https://gregobase.selapa.net/chant.php?id=4214
In this chant, all first b's on each line are flattened and valid for the whole line. No idea whether it's usual practice or if it's exceptional. The problem is obviously that when the lines in the transcription don't match the original, the flats end up in an unlogical place...

**Comment by henryso** [comment] 2018-01-04 00:39
Duplicate of #157

**Closed by henryso** 2018-01-04 00:39 UTC
