### ISSUE TITLE
\GreCPPesQuadratumLongqueueOneNothing

### ISSUE THREAD

**Issue by OldClaudio** [gregorio-project/gregorio#733] opened 2015-12-28 18:41 UTC
The above macro appears on line 187 of gregoriotex-syllable.tex (version of december 8, 2015) but it results to be undefined,
No results can be shown because after 100 errors of this kind the compilation with lualatex aborts.
Compiler: MacTeX (complete TeXLive with Mac executables) updated to december 26, 2015.

**Comment by rpspringuel** [comment] 2015-12-28 19:01
Said macro should be a pointer to the appropriate code point in the font and thus is defined when the fonts are mapped.

Can you provide a gabc file which triggers this error?

**Comment by henryso** [comment] 2015-12-28 19:01
This is a duplicate of #717, and will be fixed with Gregorio 4.0.1 which will be released within a few days.

**Closed by henryso** 2015-12-28 19:01 UTC
