### ISSUE TITLE
Mode annotation should be suppressed when initial-style is 0

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio#592] opened 2015-09-03 17:15 UTC
From Sr. M. Ruth OSB (Abbazia Mater Ecclesiae):

If a .gabc file with initial-style:0; has the “mode” field filled with something, and this file is included without commenting the "mode" field, that string appears over the first initial letter of the following score.

**Comment by rpspringuel** [comment] 2015-09-03 18:57
This is probably as simple as making sure the annotation box is empty at the end of a score.  I.e. add `\setbox\gre@box@annotation=\box\voidb@x` to the end of score macro.

**Comment by eschwab** [comment] 2015-09-03 20:06
I cannot reproduce this bug.

    name: test;
    initial-style: 0;
    mode: 4;
    annotation: 1 Ant.;
    annotation: {\color{red}VII A};

And the pdf looks as expected. I have tried moving the location of `initial-style` but that makes no difference.

**Comment by henryso** [comment] 2015-09-03 20:21
You need two scores, with the first score with initial-style:0 and mode:whatever, and the second score with initial-style:1.  Then include both.  The mode appears on the second score.

**Comment by eschwab** [comment] 2015-09-03 20:47
I get it now. Fixed by #593

**Closed by eschwab** 2015-09-03 20:47 UTC
Labels: bug, TeX
