### ISSUE TITLE
Not enough space between syllables after bemol (in some cases)

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#246] opened 2015-04-10 07:22 UTC
This bug is quite old, and I've seen it for a while : in some cases (not always, unfortunately…), there's a "clash" between syllables after a bemol. The [mwe](https://mega.nz/#!WwY1VDSY!van_MQus8wOsag2YvMaKPMmHe7alvl9_HDHsexxiWnE) illustrates that : there's the problem on *generationes* and *fores*, but not on *dicent*.

![mwe pdf](https://cloud.githubusercontent.com/assets/4775231/7087289/0132d074-df8a-11e4-8866-4581d8b3a278.png)

**Comment by henryso** [comment] 2015-04-10 10:16
Would you mind attaching an image of the output you are getting?  I think this is fixed by #244, but I am not sure.

**Comment by jperon** [comment] 2015-04-10 12:49
I've attached the image to the first comment. After compiling/installing commit `8c9db12`, the bug is there yet.

**Comment by henryso** [comment] 2015-04-10 13:01
If I understand correctly, the problem is that there is not enough space after the neumes above "ti" in "generationes" and "for" in "fores".  Correct?

**Comment by jperon** [comment] 2015-04-10 13:21
That's it.

**Comment by henryso** [comment] 2015-04-27 04:29
Just recording the mwe here for posterity...

###### mwe.tex
```
\documentclass[%                                                                 
a5paper%                       Taille de page.                                   
,11pt%                         Taille de police.                                 
,DIV=15%                       Plus grand => des marges plus petites.            
,headings=optiontoheadandtoc%  Effet des paramètres optionnels de section.       
,headings=small%                                                                 
,parskip=false%                                                                  
,openany%                                                                        
]{scrbook}                                                                       
                                                                                 
\usepackage[autocompile]{gregoriotex}                                            
\usepackage{libertine}                                                           
                                                                                 
\begin{document}                                                                 
    \includescore{test}                                                          
\end{document}
```
###### test.gabc
```
name:Beátam me dicent;
%%
(c4) Be(c.d!ewff)á(f)tam(fg~) me(g_f) di(ixf!gwh'!iv)cent(hiHG'gf.) (;) o(fg~)mnes(f') ge(f)ne(f)ra(hj)ti(ixjvvIG')ó(g/jjj'//kjjhi)nes(ih..) (::)

fo(ixfg!hi)res(hg)
```

**Comment by henryso** [comment] 2015-04-30 03:12
@jperon Are you able to test out the changes I made before I merge them?  They are on my fork at https://github.com/henryso/gregorio/tree/fix-246.

**Comment by jperon** [comment] 2015-04-30 11:57
I've just tested (after struggling a little to compile to a .deb), and the result is far better ! I let you see that below.
![bemol](https://cloud.githubusercontent.com/assets/4775231/7412238/e73faf36-ef40-11e4-87f4-ea9c8c0bd787.png)

**Closed** 2015-04-30 13:43 UTC
Labels: bug, TeX
