### ISSUE TITLE
maxbaroffset not working correctly

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#921] opened 2016-02-14 14:24 UTC
If `maxbaroffset` is set to 0, compiling `{3}(gggggggg.) *(;) 44444{4}(g)` gives

![bugbars2](https://cloud.githubusercontent.com/assets/60868/13034187/ea37347a-d32e-11e5-9748-bb96964b2ad6.png)

in which the bar is "not perfectly aligned" with the star (to say the least). Solesmes will set `maxbaroffset` to 0 so it needs to work for rc1

**Comment by eroux** [comment] 2016-02-14 14:43
The mirror problem: `{3}3333333333(g) *(;) {4}4444(g)`

**Comment by rpspringuel** [comment] 2016-02-15 21:02
The fix for this is shown in ae4444a.  I've applied it on my bar_spacing branch, but I don't think it's been applied to @eroux's fix-919.

**Comment by eroux** [comment] 2016-02-15 22:01
I've cherry-picked your changes, the new result is

![bugbars](https://cloud.githubusercontent.com/assets/60868/13061371/f9ee3012-d437-11e5-9c18-cc5b2440b09d.png)

so I wouldn't say this is fixed, but it's a first step!

**Comment by rpspringuel** [comment] 2016-02-15 22:05
This is a case where fixing one bug (the fact that the offset limit wasn't working correctly), drives you into another (large offsets can cause overlap between elements).

**Comment by rpspringuel** [comment] 2016-02-16 00:39
Oops.  Just realized I hit the wrong button on my last comment.

**Comment by eroux** [comment] 2016-02-18 14:19
The most annoying case is fixed, see https://github.com/gregorio-project/gregorio/pull/932#issuecomment-185676758 for an example of a rare case where the bug remains

**Comment by rpspringuel** [comment] 2016-02-19 16:46
In creating a test for #933 I noticed what looks like a sign error in this:

```% !TEX program = LuaLaTeX+se
\documentclass{article}

\usepackage{gregoriotex}

\begin{document}
Show difference between offset limits for a bar and a no-bar syllable

\gresetbarspacing{new}
\gabcsnippet{(c3) kill(g) 1(gggggggg) *(:) 22222{2}(g) 1(gggggggg) *() 22222{2}(g)}

\end{document}
```

Produces
![temp](https://cloud.githubusercontent.com/assets/7671682/13182151/5afa8b3a-d6fe-11e5-8742-ac23b2c9df7f.png)

Those stars are clearly being moved in the wrong direction.

**Comment by eroux** [comment] 2016-02-19 16:49
That's really strange... thanks for reporting

**Comment by rpspringuel** [comment] 2016-02-19 19:37
I did some looking and found some errors, the fixing of which improved things a bit:

![temp](https://cloud.githubusercontent.com/assets/7671682/13186816/f200cbcc-d715-11e5-8511-e69d327e7a9f.png)

Clearly it's not completely done, but I'm fairly certain the problem is inside the algorithm which I don't completely understand (I've played with just about everything else just to prove myself that it isn't).  I'll leave it to @eroux to continue sorting this out.

**Comment by eroux** [comment] 2016-02-19 22:22
I'll try to explain once more the algorithm (in the case I've fixed). When I'll reference line number, they'll be those in [this version](https://github.com/gregorio-project/gregorio/blob/8463776f1486bbf49b0e33da9526b58f7e4c04f9/tex/gregoriotex-spaces.tex)

So, if the offset between the bar and the text is too important:

#### First step

push the text right so that it has the correct offset, done by line 1016. If I comment the rest of the lines I get:

![step1](https://cloud.githubusercontent.com/assets/60868/13190158/c5a2447a-d75b-11e5-957b-a1b3e453bc3e.png)

Now the text and the line are aligned correctly.

#### Second step

2. if the text is too far right (which it is in our case, detected by line 1019), then push both the bar and the text left of the minimal amount to get the text right, this is done by lines 1020 and 1021. If I comment the rest of the lines I get:

![step2](https://cloud.githubusercontent.com/assets/60868/13190250/6b349776-d75c-11e5-89a9-8366a598c577.png)

so now, the text and the line are still aligned correctly, and the text is at the correct distance of the following syllable.

#### Third step

Now if the bar has been pushed right too much (as in our case, detected by line 1025/1026), we push both the bar, the text of the note and the syllable right so that the bar is at the minimum distance of the notes of the left, this is done by the lines 1027 to 1029. The final result is 

![step3](https://cloud.githubusercontent.com/assets/60868/13190760/71353ed4-d75f-11e5-9db6-fa3a0ea16a24.png)

**Comment by rpspringuel** [comment] 2016-02-20 04:11
Thank you for that.  I was able to follow that and figure out the problem.  I'm now working on mirroring the algorithm for the other direction.

**Closed** 2016-02-20 18:22 UTC
Labels: bug, TeX
