### ISSUE TITLE
Spacing problem before stars under bars

### ISSUE THREAD

**Issue by jperon** [gregorio-project/gregorio#238] opened 2015-04-08 09:32 UTC
Perhaps it's related to #221 ? There's not enough space before stars that are under bars. See the example joined, especially in the verse.
![00-document](https://cloud.githubusercontent.com/assets/4775231/7042530/d64018f2-dde2-11e4-96a9-d4251e839a9a.png)

**Comment by eroux** [comment] 2015-04-08 09:38
What version/branch do you use?

**Comment by jperon** [comment] 2015-04-08 09:40
I use the default one when pulling the repo.

**Comment by eroux** [comment] 2015-04-08 09:41
do you specify the `develop` branch or is it the `master` branch that is checked out?

**Comment by jperon** [comment] 2015-04-08 09:42
It's the master one.

**Comment by rpspringuel** [comment] 2015-04-08 15:50
When did you last update?  The master branch was just updated this past weekend with the 3.0.0 release candidate.  Is that what you're using?

If it is and you're not a new user, did you see this behavior before updating?

Finally, please post a minimal example of the `gabc` that reproduces the problem.  The main `tex` file might also come in handy.

**Comment by jperon** [comment] 2015-04-09 09:53
Yes, I'm using a recently updated master branch. I didn't see this
behaviour before updating.
You'll find a mwe joined to this mail. I just let the first half of the
verse, that's significant enough.

Writing this mwe, I saw two other bugs : the default size of the initial
(at least with libertine) seems too small, and there should be an hyphen
within "Exal*-*tábo". Should I open other issues for those ?

2015-04-08 17:50 GMT+02:00 Br. Samuel Springuel <notifications@github.com>:

**Comment by jperon** [comment] 2015-04-09 09:55
The file…

2015-04-09 11:53 GMT+02:00 Jacques Peron <abbe.jacques.peron@gmail.com>:

**Comment by eroux** [comment] 2015-04-09 09:57
Sorry, I don't think you can attach any type of file in github messages (never tested before, sorry), can you send this to `gregorio-devel@gna.org`?

**Comment by eroux** [comment] 2015-04-09 10:31
Thanks, I believe it's also visible on the example in the repository... I just didn't manage to get the output of the example on an old repository... @rpspringuel as you did most of the code about spaces, would you have time to take a look?

**Comment by rpspringuel** [comment] 2015-04-09 12:19
I'll take a look later today or tomorrow.

**Comment by rpspringuel** [comment] 2015-04-09 17:36
@jperon, on the other two issues you noted:

1. The default initial size is somewhat on the small size, but that comes from not assuming that a infinitly scalable font is loaded.  As a result we are restricted to the default LaTeX sizes.  A one line initial uses `\huge` and a two line initial uses `\Huge`.  These are as big as LaTeX gets out of the box.   To go bigger you have to load a font that supports infinite scaling.  That requires packages beyond GregorioTeX, so to avoid adding a dependency, we don't assume that you will. 
2. I'll look closer at the hyphenation issue, but I suspect it's related to the timing of spacing decisions.  GregorioTeX makes the decision on whether or not to include a hyphen as it moves from one syllable to the next and so the decision is based on the relative size of the notes and text of the two syllables. However, these spaces are rubber, which means the when the end of a line is reached, they sometimes get stretched in order to make the line justified.  This stretching is done without revisiting the hyphenation decision. Indeed, I'm not sure how one would get that to happen since the line breaks are handled by LuaLaTeX not GregorioTeX. The printing of the hyphen would have to be conditional on the size of the stretch.  You might open another issue for this one, but if my surmises are correct (and I've made them without testing your code, so I could be wrong) then I wouldn't expect a fix for this in 3.0.0.

**Comment by eroux** [comment] 2015-04-09 17:54
About hyphenation, it would be possible to correct the behaviour in the lua callback where gregoriotex already hooks, it wouldn't be straightforward, but possible... But not for 3.0, sure.

**Comment by jperon** [comment] 2015-04-09 20:19
About 1, I must admit I don't understand very well this reason : as GregorioTeX, in practice, depends on LuaLaTeX, and LuaLaTeX clearly recommends loading fontspec (cf `texdoc lualatex`), wouldn't it be better, for newbies, to have by default a good initial size rather than having to tweak the settings, event at the cost of a new dependency ?

But once again, perhaps it would be better to open another issue for each one of these problems ?

**Comment by henryso** [comment] 2015-04-10 10:28
Doing that would mean GregorioTeX would load fontspec rather than leaving the decision on font handling to the user.  One possibility is that Gregorio can attempt to detect if fontspec is loaded and define different macros for the initial, but that might be surprising behavior.

**Comment by jperon** [comment] 2015-04-10 13:33
It might be, but this surprise would be, for those who don't use fontspec, the same as it is now for all. I guess those persons would be : 
- or newbies, who should use fontspec anyway (and this would indicate it to them) ;
- or texperts, who then would know what to do.

But it's only my own view, evidently.

**Comment by rpspringuel** [comment] 2015-04-10 18:40
Please open a new issue to discuss the defaults for the initial. The conversation is getting to involved to be tackled here without distracting from the current issue. 

On the problem reported here, @jperon please try moving the `%` from the beginning of line 770 in `gregoriotex-syllable.tex` to the end and tell me what you think of the results. I don't think this is a final solution, but it may work for now, and given that I can't upload commits at the moment (my internet connection is acting up again) it may be all I can do for the moment.

**Comment by jperon** [comment] 2015-04-10 19:39
I guess you where spoking of the line `%\kern\gre@skip@temp@three ` (line 778 as of commit `8c9db12`).
The result is better uncommenting that line, but I personally like much more the result that I obtain by replacing `@three` with `@one`, which gives the following : 
`\kern\gre@skip@temp@one %`

**Comment by rpspringuel** [comment] 2015-04-10 20:21
Yes, that's the line.  I'm making changes based on v3.0.0-rc1. Changes to `gregoriotex-syllable.tex` since then may have moved the line. 

The problem with changing to `skip@temp@one` is the value stored there isn't related to the the bar or its syllable at all.  It's a carryover value from some previous calculation (which one, I don't know)and thus could be wildly different depending on what appears before the bar.  While it may work for you here, it would probably break dramatically in other situations. 

Another small tweak, make line 660 read:
    \gresyllablenotes{#9 }%

I'm not sure why this works, but it appears to make the relative alignment between the star and the bar better (i.e., the bar will be centered above the star, currently they're off by a bit).

**Comment by jperon** [comment] 2015-04-11 07:05
Yes, restoring `@three` and changing line 668 (now) as you say gives a very good result : 

![gaudensgaudebo_quasi pdf](https://cloud.githubusercontent.com/assets/4775231/7100558/b06aa676-e029-11e4-83c0-2e093e7cfb43.png)

**Comment by henryso** [comment] 2015-04-11 12:01
These two tweaks make the output of https://github.com/gregorio-project/gregorio-test/blob/master/tests/gabc-dump/glyphs/bars.gabc closer to what I had recorded prior to 3.0.0-rc1's release.

**Comment by eroux** [comment] 2015-04-11 20:05
I'm affraid adding a space in `\gresyllablenotes` just adds a space, which might make things look better, but is just a patch on a real problem that, I believe, needs fixing... A space in TeX also introduces a penalty, which might change the way lines break.

**Comment by rpspringuel** [comment] 2015-04-11 21:02
@eroux, you're right.  I just wish I could figure out why it makes a difference.  Then maybe I could track down the actual problem.

**Comment by rpspringuel** [comment] 2015-04-12 18:35
Gah!  I think I found the problem.  For some reason TeX thinks that the bar lines have negative width!  Or at least it does when inside `\grebarsyllable` and printing a minima, minor, maior, or dominica.  Inside `\grewritebar` I get a positive width that makes sense.  Additional testing shows that the values for finalis and virgula inside `\grebarsyllable` are also under what they are in `\grewritebar`, though not enough to go negative.  I don't know why the values are different in these two places, but if I manually force `\grebarsyllable` to match the value in `\grewritebar` then things align as expected.  Now to figure out how to make that happen automatically.

**Comment by rpspringuel** [comment] 2015-04-12 19:05
Found a somewhat hackish fix.  Please check #255 and see what you think.

**Comment by jperon** [comment] 2015-04-15 14:39
Excuse me for my silence : I'm not at home, and don't have an internet access on a regular basis this week. I'll test all that this week-end.

**Closed** 2015-04-15 17:57 UTC
Labels: bug, TeX
