### ISSUE TITLE
problem with virga strata oriscus orientation

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#972] opened 2016-02-27 21:58 UTC
Compiling

```
quó(efO)mo(e)do(e Z) quó(e!fo)mo(e)do(e)
```

I get

![bubugue](https://cloud.githubusercontent.com/assets/60868/13375634/486777aa-dda5-11e5-96dc-3252b58bd3ea.png)

the "correct" result according to automatic oriscus orientation is the second one while default is the first one ("wrong"). Is this intentional? I'm not really sure what the state of things are in this area... If this can be easily fixed then let's do it, otherwise we can keep it for a future release...

**Comment by henryso** [comment] 2016-02-27 23:13
This is actually one of the cases where the complications in implementation (new glyphs need to be drawn and quite a few other things) led me to request pushing the full implementation of oriscus scapus direction to the next release.  I'd hold off on this.

**Comment by eroux** [comment] 2016-02-28 08:13
Ok good, thanks!

**Comment by henryso** [comment] 2016-03-03 22:19
I think this too big for a patch-fix.

**Comment by eroux** [comment] 2016-03-04 07:07
ok

**Comment by henryso** [comment] 2016-03-11 20:33
This is pretty much a duplicate of #898, so should #898 also be in 4.2?  It's a pretty big overhaul.

**Comment by eroux** [comment] 2016-03-11 21:14
I think so yes, end of April is not a very strong necessity, it can be delayed (most of the bug needed by big projects were addressed in 4.1.1)

**Closed** 2016-03-14 13:50 UTC
Labels: question
