### ISSUE TITLE
issue with beta2 under Windows

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#894] opened 2016-02-09 18:52 UTC
See [this thread](https://mail.gna.org/public/gregorio-users/2016-02/msg00042.html) and [this one](https://mail.gna.org/public/gregorio-users/2016-02/msg00044.html). Solesmes has this problem too (under TeXLive 2015).

**Comment by eroux** [comment] 2016-02-09 18:57
It seems the common denominator is Windows... maybe a problem in the installer?

**Comment by eroux** [comment] 2016-02-09 20:41
If it's a problem in the installer, don't hesitate to publish a beta3 today, maybe just for Windows (no mac, no tarball, no pdf), so that people with broken systems can be on rails soon.

**Comment by rpspringuel** [comment] 2016-02-09 22:04
I don't have a solution yet, but I've been able to reproduce the problem on my Windows 10 VM w/ TeXLive 2015.  Looking at the console it appears that the hang up occurs during the loading of `gregoriotex.lua`.  Indeed, it looks like I'm getting a lua prompt, which is something I thought that texlua couldn't do.  I'll continue investigating later tonight.

**Comment by rpspringuel** [comment] 2016-02-09 22:48
I have not had a chance to test yet, but I think the problem is that `gregoriotex-symbols.lua` wasn't added to the installation manifest for the Windows installer.

**Comment by henryso** [comment] 2016-02-09 23:25
Hmm... I added that file, and I think I forgot it in all the manifests.  I will fix that now.  Apologies.

**Comment by henryso** [comment] 2016-02-09 23:35
I merged in the change as an emergency measure.  Please review 3b6d035fd043e32e2a2511a2b9319ef83d387d84.

**Comment by rpspringuel** [comment] 2016-02-10 04:31
See #896

**Closed** 2016-02-12 04:01 UTC
Labels: bug, TeX
