### ISSUE TITLE
changing default spaces

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio#1182] opened 2016-07-10 14:09 UTC
Many of the current spaces have not been carefully chosen (by me), and I think changing them is only possible for quite big projects as it requires to understand how the spacing work, which is not obvious. So having better default spaces should be quite beneficial to many. The Antiphonale Monasticum projects allowed us to take the spaces they use, I'll make a pull request and we can discuss them

**Comment by eroux** [comment] 2016-11-21 11:22
Here are the spaces used by the italian Antiphonale Project:

```tex
\grechangedim{annotationraise}{-2mm}{scalable}
\grechangedim{beforeinitialshift}{2mm}{scalable}%
\grechangedim{afterinitialshift}{2mm}{scalable}%
\greseteolhyphen{normal}

\grechangedim{moraadjustment}{0.05 cm}{scalable}%
\grechangedim{moraadjustmentbar}{0.05 cm}{scalable}%
%\grechangedim{alterationadjustmentbar}{0.07 cm}{scalable}%
\grechangedim{bar@virgula@standalone@notext}{0.2 cm}{scalable}%
\grechangedim{bar@minima@standalone@notext}{0.2 cm}{scalable}%
\grechangedim{bar@minor@standalone@notext}{0.2323 cm}{scalable}%
\grechangedim{bar@dominican@standalone@notext}{0.2323 cm}{scalable}%
\grechangedim{bar@maior@standalone@notext}{0.2323 cm}{scalable}%
\grechangedim{bar@finalis@standalone@notext}{0.2323 cm}{scalable}%
\grechangedim{bar@finalfinalis@standalone@notext}{0.29169 cm}{scalable}%
\grechangedim{bar@rubber}{0 cm plus 0.025cm minus 0.025 cm}{scalable}%
\grechangedim{bar@minima@short}{0.12 cm plus 0.05 cm minus 0.00469 cm}{scalable}%
\grechangedim{bar@virgula@short}{0.13 cm plus 0.05 cm minus 0.00469 cm}{scalable}%
%\grechangedim{bar@finalfinalis@standalone@notext}{0.2323 cm}{scalable}%
\grechangedim{interwordspacetext@bars@notext}{0.19 cm}{scalable}%
\grechangedim{interwordspacetext@bars@notext@euouae}{0.18 cm}{scalable}%
\grechangedim{interwordspacetext}{0.17 cm plus 0.05 cm minus 0.05 cm}{scalable}%
\grechangedim{interwordspacenotes@euouae}{0.23 cm plus 0.1 cm minus 0.05 cm}{scalable}%
\grechangedim{interwordspacenotes}{0.29 cm plus 0.05 cm minus 0.05 cm}{scalable}%
\grechangedim{interwordspacetext@euouae}{0.21 cm plus 0.1 cm minus 0.05 cm}{fixed}%
\grechangedim{maxbaroffsettextright}{0.15 cm}{scalable}%
\grechangedim{maxbaroffsettextleft}{0.3 cm}{scalable}%

\grechangedim{spaceafterlineclef}{0.23 cm plus 0 cm minus 0.01367 cm}{scalable}%
\grechangedim{spacebeforeeolcustos}{0.23 cm plus 0 cm minus 0 cm}{scalable}%
\grechangedim{shortspaceafterlineclef}{0.18 cm plus 0 cm minus 0.01367 cm}{scalable}%

\grechangedim{spaceabovelines}{0.45576 cm plus 0.45576 cm minus 0.20114 cm}{scalable}%
\grechangedim{emergencystretch}{1mm}{scalable}

\grechangedim{baselineskip}{11.5pt}{scalable}%

\gresetcustosalteration{invisible}
```

Now I'm not totally sure what to do with it... Although I think they are reasonable defaults, changing them in the test repository will have a big impact and it will be impossible to review the diff and know when a bug cannot be spotted anymore because of the change in spaces... so maybe having a `gsp-pre5` with the current spaces (which we'd use in the test repository)  and use these new ones in the `gsp-default`? Wdyt?

**Comment by rpspringuel** [comment] 2016-11-21 14:04
I'm not sure what the problem is.  If done on its own branch then the changes caused by these spacing changes would be separate from any due to other changes already in progress.

**Comment by eroux** [comment] 2016-11-21 14:11
My point is that there are certainly many tests that depend on some special circumstances, like some line breaks here or there, and if spaces are not the same, the original bug will not be shown anymore, and thus the test will be made irrelevant

**Comment by rpspringuel** [comment] 2016-11-21 19:15
That's an issue with any subsequent change.  Granted, changing the spaces is more pervasive, but the change to the bar spacing algorithm was similarly pervasive. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment] 2016-11-21 19:15
I think we should do a best-effort pass through the tests to determine which ones look specifically at things like line endings and put comments in the tests themselves to call that out.  Certainly, for the fix-XXXX tests, we can refer back to the issues themselves.  Then, we take those identified tests and apply whatever technique necessary to keep them testing whatever they are testing and then just accept the rest using the new spacing configuration.

**Comment by eroux** [comment] 2016-11-22 18:16
ok for that! I'm affraid I won't have time to do that any time soon though, end of this year will be quite busy...

**Comment by henryso** [comment] 2016-12-19 18:18
https://github.com/gregorio-project/gregorio/pull/1266#issuecomment-267811773 indicates that there are a few more interline spacings that need to change, so I'm not closing this issue yet.

**Comment by eroux** [comment] 2017-01-05 12:43
The values for horizontal spacing that the Italian Antiphonale is using are:

```tex
\grechangedim{spaceabovelines}{0 cm}{scalable}%
\grechangedim{emergencystretch}{1mm}{scalable}
\grechangedim{parskip}{1pt plus 1pt}{scalable}%
\grechangedim{lineskip}{0pt plus 1pt}{scalable}%
\grechangedim{baselineskip}{55pt plus 5pt minus 5pt}{scalable}%
```

the results are quite good...

**Comment by henryso** [comment] 2017-01-05 12:54
Other than `emergencystretch`, you mean vertical spacing, no?

**Comment by eroux** [comment] 2017-01-05 12:57
sorry, yes indeed! Well, maybe `emergencystretch` could be ignored here, I'm not entirely sure...

**Comment by henryso** [comment] 2017-01-05 19:09
I'll leave `emergencystretch` as `\the\emergencystretch`, as described in #1266.

**Comment by henryso** [comment] 2017-01-05 19:20
This is personal opinion, but looking at the results, I feel like a `spaceabovelines` of `0 cm` is too small.  Probably the old value (`0.45576 cm plus 0.45576 cm minus 0.20114 cm`) is too big, but setting this to `0 cm` could mislead the eye (at least mine) to thinking the text goes with the line below.

![image](https://cloud.githubusercontent.com/assets/421318/21694192/fc268bee-d351-11e6-9eb6-2a9b093b3cee.png)

**Comment by eroux** [comment] 2017-01-05 19:24
I think you're getting this impression because most lines have very low notes, but on a more regular score it looks nice... professional books are printed with these settings so I don't think it's a problem... If you have books with scores with such a large ambitus, then changing it is probably a good idea, but I think 95% of users only have more "regular" scores... what do you think?

**Comment by henryso** [comment] 2017-01-05 19:44
Well, I think that's a typical score, but this is only my opinion, so I'm willing to give up my argument.

**Comment by eroux** [comment] 2017-01-05 19:56
Hmmm, that's not my experience (I'm currently proofreading the italian Antiphonale, which is quite big), but it certainly depends on the type of book, and maybe it should be indicated somewhere that if most scores have very low notes, `spaceabovelines` should be augmented... or maybe we should take the opposite approach? I don't know... anyway we should find a way to document it

**Comment by henryso** [comment] 2017-01-05 20:01
I actually feel this way because of the *high* notes on the staff below, not because of the low notes on the staff above.  But again, this is my opinion, and of course I can set my own personal value to whatever I want.

**Comment by eroux** [comment] 2017-01-05 20:06
Yes, but both things count, the reason why it looks like the text is belonging to the notes below is also becaue it's far from the notes above, because of the low notes involving a big distance between the text and corresponding notes

**Comment by henryso** [comment] 2017-01-05 20:21
Since my argument/opinion is not very strong, I'll drop it.

Regarding what you said earlier about documenting this: what is the best way to document this?  I can add it to the GregorioRef PDF, but I don't think many people would find it easily there.

**Comment by eroux** [comment] 2017-01-05 20:24
Well... that's certainly a good question... I think it would have its place in a medium-level tutorial, but we don't have that, and it's hard to fit it somewhere... maybe in the tips and tricks section, something about tuning the vertical spaces? It's really not an obvious part, I can write it myself if you want.

**Comment by henryso** [comment] 2017-01-06 02:10
Because this affects all of the multi-line gabc-output tests, I am going to hold off on updating the expectations and creating the pull request for the new spaces until #1273 and #1274 are reviewed and merged (or rejected).

**Comment by henryso** [comment] 2017-01-07 13:07
Leaving this open for @eroux to implement documentation as noted above.

**Closed** 2017-04-15 13:26 UTC
Labels: enhancement, TeX
